#!/usr/bin/env node
/**
 * One-time seed for the Booking Types fact: your booking pages' meeting types.
 * Parsed by booking-types.mjs; availability lives in the Scheduling Agent Config
 * (seed-scheduling.mjs). The three types below are STARTERS on placeholder hosts:
 * edit them in NOAN — hosts, links, questions — and the pages follow within 5 minutes.
 *
 * Never overwrites: an existing block is reported and left alone.
 *
 * Run:  NOAN_AGENT_API_KEY=... node agents/seed-booking.mjs
 */
import { pathToFileURL } from "node:url";
import { noanGetAll, noanPost } from "./noan.mjs";

export const BLOCK_TITLE = "Booking Types";

export const FACT = `Meeting types for your booking pages. Edit here; the pages pick up changes
within 5 minutes. When a host is free (hours, timezone, buffer, blocked dates) lives
in the Scheduling Agent Config. Each host's hours are read in THEIR OWN Google
Calendar timezone, so a host's page follows them when they travel.

One "## Name" section per type, "key: value" lines:
- link: <handle>/<slug>, the page address. Changing it breaks links already sent.
- host: a teammate's email (their calendar is booked). host name: shown on the page.
- length minutes, step minutes (default 30), buffer minutes, min notice hours, max days out.
- hours Fri: 09:00-13:00 sets this type's week, in the host's own timezone ("off" closes a
  day). Any day with no line here uses the Scheduling Agent Config's week.
- timezone: Europe/Berlin pins the zone those hours are read in, instead of following
  the host's Google Calendar. Guests always see times in their own zone either way.
- blocked dates: 2026-12-24, 2026-12-25 are THIS host's days off ("none" clears them).
- title: the calendar event's name; {guest} and {type} are filled in.
- description: one line shown on the page.
- questions: one "- Label | kind | required" line each. Kinds: text, long, company,
  title, website, phone, linkedin, location. Website and phone fill the contact's
  empty fields; every answer goes in the contact memo.
- contact tags: existing NOAN tags added to the guest's contact.
- on book: task owner host | task owner agent | task tag <agent trigger tag> | no task
- on cancel: close task | keep task | task tag <agent trigger tag>

A type with a mistake is skipped (the rest keep working) and the reason is logged.

## Intro Call
link: alex/intro
host: founder@example.com
host name: Alex Founder
length minutes: 30
min notice hours: 4
max days out: 60
title: {guest} and Alex Founder
description: A first conversation: what you're working on and whether we can help.
questions:
- Company | company | required
- Company website | website
- What would you like to talk about? | long
contact tags: Lead
on book: task owner host
on cancel: close task

## Working Session
link: alex/working-session
host: founder@example.com
host name: Alex Founder
length minutes: 60
buffer minutes: 15
min notice hours: 24
max days out: 60
title: Working session: {guest} and Alex Founder
questions:
- Company | company
- What should we get done? | long | required
on book: task owner host
on cancel: close task

## Customer Check-in
link: sam/check-in
host: teammate@example.com
host name: Sam
length minutes: 30
min notice hours: 12
max days out: 30
hours Mon: 10:00-16:00
hours Tue: 10:00-16:00
hours Wed: 10:00-16:00
hours Thu: 10:00-16:00
hours Fri: off
title: {guest} and Sam
description: 30 minutes on getting more out of the product: what to set up next, and anything that isn't working.
questions:
- Company | company
- Anything you'd like to cover? | long
on book: task owner host
on cancel: close task
`;

/* ---- seeding (generated by the export) ----
 * Find or create this service's own stack (SEED_STACK_TITLE overrides the name), create
 * each block only if it is missing, and write a fact ONLY into a block created in this run:
 * POST /facts replaces a block's whole fact, so re-running this can never overwrite your
 * own edits. Prints the env lines to set. */
const STACK_TITLE = process.env.SEED_STACK_TITLE || "Booking Config";
const SEED_BLOCKS = [
  {
    "title": "Booking Types",
    "description": "Booking pages: meeting types, questions, tags and who each booking goes to. Edit here.",
    "envVar": "BOOKING_TYPES_BLOCK_SLUG"
  }
];
const SEED_FACTS = { "Booking Types": FACT };
const same = (a, b) => String(a || "").trim().toLowerCase() === String(b || "").trim().toLowerCase();

async function findBlock(title) {
  const items = await noanGetAll(`/blocks?custom_only=true&title=${encodeURIComponent(title)}&per_page=100`);
  return (items || []).find(b => same(b.title, title)) || null;
}

async function ensureStack(first) {
  const stacks = await noanGetAll("/stacks?custom_only=true");
  const hit = (stacks || []).find(s => same(s.title, STACK_TITLE));
  if (hit) return { id: hit.id, created: null };
  // POST /stacks needs at least one block, so the stack is born with the first block we need.
  const res = await noanPost("/stacks", {
    title: STACK_TITLE,
    description: "Your booking pages' instructions: meeting types and availability. The booking service re-reads these facts every 5 minutes.",
    blocks: [{ title: first.title, description: first.description }],
  });
  const id = res?.stack?.id || res?.id;
  if (!id) throw new Error(`could not create the "${STACK_TITLE}" stack (no id in the create response)`);
  console.log(`created the "${STACK_TITLE}" stack`);
  return { id, created: first.title };
}

async function main() {
  const env = {};
  let stack = null;
  for (const b of SEED_BLOCKS) {
    const existing = await findBlock(b.title);
    if (existing) {
      console.log(`"${b.title}" exists → ${existing.slug} (fact untouched)`);
      env[b.envVar] = existing.slug;
      continue;
    }
    stack = stack || await ensureStack(b);
    if (stack.created !== b.title) {
      const res = await noanPost(`/stacks/${stack.id}/blocks`, { title: b.title, description: b.description });
      if (!(res?.block?.slug || res?.slug)) throw new Error(`could not create "${b.title}" (no slug in the create response)`);
    }
    const slug = (await findBlock(b.title))?.slug;
    if (!slug) throw new Error(`created "${b.title}" but cannot find its slug`);
    await noanPost("/facts", { blockSlug: slug, content: SEED_FACTS[b.title] });
    console.log(`created "${b.title}" → ${slug}`);
    env[b.envVar] = slug;
  }
  console.log("\nAdd to your deploy env:");
  for (const [k, v] of Object.entries(env)) console.log(`${k}=${v}`);
}

const entry = process.argv[1] ? pathToFileURL(process.argv[1]).href : null;
if (entry && import.meta.url === entry) {
  main().catch(e => { console.error("seed failed:", e.message); process.exit(1); });
}
